### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [Miromani4/traefik-plugin-AdminAPI_WebUI#1]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
failed to run the plugin with Yaegi: the function `New` of test produce a panic: panic during the call of the function: open /admin_panel/html/web_panel.zip: no such file or directory
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.traefik.io/).

**Comment by Miromani4** [comment]
fit it
